services:
  tempo:
    image: grafana/tempo@sha256:7541828fa9babc02ebf2b13d344759558ae2e68418a3a6919e8bc7f62452f1f9
    command: [ "-config.file=/etc/tempo.yaml" ]
    user: "0:0"
    volumes:
      - tempo_data:/tmp/tempo
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200"  # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
    networks:
      - o11y
  loki:
    image: grafana/loki@sha256:4c431d2e6b9b38718694b31c5d56be7c80dc69c513215fde1aeb5b02cd4e2665
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - o11y
  collector:
    image: otel/opentelemetry-collector-contrib:0.69.0
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8090"
    volumes:
      - ./collector/collector.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - o11y
  prometheus:
    image: prom/prometheus@sha256:78ed1f9050eb9eaf766af6e580230b1c4965728650e332cd1ee918c0c4699775
    command:
      - "--enable-feature=remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - o11y
  grafana:
    image: grafana/grafana-enterprise@sha256:db6e5cd3e2f368e96935ffdd06f4dedc2391f09017c657661395dbce4a30d99e
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/vaadin-dashboard.json:/var/lib/grafana/dashboards/vaadin-dashboard.json
      - ./grafana/vaadin-frontend-dashboard.json:/var/lib/grafana/dashboards/vaadin-frontend-dashboard.json
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "tempoApmTable"
    ports:
      - "3000:3000"
    networks:
      - o11y
  demo:
    image: vaadin/observability-kit-demo
    environment:
      - OTEL_JAVAAGENT_CONFIGURATION_FILE=/workspace/agent.properties
      - OTEL_JAVAAGENT_DEBUG
      - VAADIN_OFFLINE_KEY
    volumes:
      - ./agent.properties:/workspace/agent.properties
    ports:
      - "8080:8080"
    networks:
      - o11y
    profiles:
      - full
volumes:
  prometheus:
    driver: local
  grafana_data:
    driver: local
  tempo_data:
    driver: local
networks:
  o11y:
